//! Deterministic benchmark workload generation.
//!
//! Rust owns "Workload generation" in the ownership matrix of
//! `docs/contracts/polyglot_boundaries.md`. This crate generates a seeded
//! prompt workload and writes it to `<runs_root>/<run_name>/workload.jsonl`
//! (plus a companion `workload_manifest.json`), which Python and Julia read
//! back as plain files. There is no FFI and no cross-language runtime
//! dependency: the JSONL file *is* the interface.
//!
//! # Determinism
//!
//! The same `(seed, count, workload, max_tokens, stream)` spec produces a
//! byte-for-byte identical `workload.jsonl` on any machine, any OS, and any
//! rustc version. That is the whole point of the crate — a benchmark you
//! cannot replay is not a benchmark. `max_tokens` and `stream` belong to
//! that key because both are copied verbatim into every row; only
//! `run_name` is excluded, since it names the directory and never appears
//! in a row. (Prompt *text* alone depends on just `(seed, count, workload)`.)
//! To keep that promise the generated bytes contain:
//!
//! * no timestamps, hostnames, usernames, or paths,
//! * no entropy-seeded RNG (the PRNG below is seeded only from `seed`),
//! * no `HashMap`/`HashSet` iteration (which is randomized per process),
//! * no floating-point formatting,
//! * a fixed JSON field order, from the declaration order of
//!   [`WorkloadRequest`].
//!
//! The PRNG is a hand-rolled SplitMix64 rather than the `rand` crate:
//! `rand`'s stream is explicitly not guaranteed stable across versions, so a
//! routine dependency bump would silently change every generated workload.

use std::fs;
use std::path::{Component, Path, PathBuf};

use anyhow::{bail, Context, Result};
use serde::Serialize;

/// Schema version stamped on every generated row and on the manifest.
///
/// Bump this only for a breaking change to the row shape; new optional
/// fields are backward-compatible per `docs/contracts/polyglot_boundaries.md`.
pub const WORKLOAD_SCHEMA_VERSION: u32 = 1;

/// Default PRNG seed, used when the caller does not pick one.
pub const DEFAULT_SEED: u64 = 42;

/// File name of the generated JSONL workload inside `<runs_root>/<run_name>/`.
pub const WORKLOAD_FILE_NAME: &str = "workload.jsonl";

/// File name of the companion manifest inside `<runs_root>/<run_name>/`.
pub const WORKLOAD_MANIFEST_FILE_NAME: &str = "workload_manifest.json";

/// Upper bound on [`WorkloadSpec::count`].
///
/// [`generate_workload`] materializes every request in memory, so an
/// unbounded count turns a typo (`--count 100000000000`) into an OOM. One
/// million rows is roughly 100 MB of JSONL — far past any plausible serving
/// benchmark, but small enough to fail fast instead of thrashing. Raise this
/// deliberately (and switch to a streaming writer) if a real workload ever
/// needs more.
pub const MAX_REQUEST_COUNT: usize = 1_000_000;

/// Upper bound on [`WorkloadSpec::workload`], in bytes.
///
/// The label is cloned into every generated row, so bounding
/// [`MAX_REQUEST_COUNT`] alone does not bound memory: a 100 KB label at the
/// maximum count would allocate over 100 GB of labels before the JSONL
/// buffer is even built, OOM-ing the process instead of failing fast. A
/// label is a short name like `inference`, so 256 bytes is already generous.
pub const MAX_WORKLOAD_LABEL_LEN: usize = 256;

/// Name recorded in the manifest as the producer of these files.
pub const GENERATOR_NAME: &str = "agoge-benchgen";

/// Prompt fragments. These are `const` tables baked into the binary on
/// purpose: reading fragments from an external file or the network would make
/// the output depend on something outside `(seed, count, workload)`.
const PROMPT_TASKS: &[&str] = &[
    "Summarize",
    "Explain",
    "Write a short guide to",
    "List three trade-offs in",
    "Draft a changelog entry for",
    "Critique the design of",
    "Outline a test plan for",
    "Describe the failure modes of",
];

const PROMPT_TOPICS: &[&str] = &[
    "QLoRA fine-tuning on a single 16GB GPU",
    "gradient checkpointing",
    "4-bit weight quantization",
    "safetensors versus pickle checkpoints",
    "LoRA target module discovery",
    "dataset deduplication for instruction tuning",
    "KV cache eviction policies",
    "speculative decoding",
    "tokenizer padding and truncation",
    "learning-rate warmup schedules",
];

const PROMPT_QUALIFIERS: &[&str] = &[
    "assume a reader who has never trained a model",
    "keep it under 100 words",
    "cite concrete numbers",
    "answer as a bulleted list",
    "call out anything that would corrupt a run",
    "compare against the naive approach",
];

/// Maximum number of qualifier clauses appended to a prompt.
const MAX_QUALIFIERS: u64 = 3;

/// SplitMix64 — a tiny, fully specified PRNG.
///
/// Self-contained by design (see the crate-level determinism note): the
/// algorithm is fixed here in source, so the stream cannot drift under us.
struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    const GAMMA: u64 = 0x9E37_79B9_7F4A_7C15;

    fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    /// Advances the state and returns the next 64-bit output.
    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(Self::GAMMA);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Returns a value in `0..n`, uniformly and without modulo bias.
    ///
    /// Rejection sampling keeps the result unbiased while staying
    /// deterministic: the rejection test depends only on the PRNG stream, so
    /// the same seed always rejects the same draws. Returns `0` for `n == 0`
    /// rather than panicking.
    fn next_range(&mut self, n: u64) -> u64 {
        if n == 0 {
            return 0;
        }
        // Largest multiple of `n` that fits in a u64; drawing only below it
        // makes every residue class equally likely.
        let limit = u64::MAX - (u64::MAX % n);
        loop {
            let value = self.next_u64();
            if value < limit {
                return value % n;
            }
        }
    }

    /// Picks one entry from a non-empty `const` table.
    fn pick<'a>(&mut self, table: &[&'a str]) -> &'a str {
        debug_assert!(!table.is_empty(), "prompt tables must not be empty");
        let index = self.next_range(table.len() as u64) as usize;
        table[index]
    }
}

/// FNV-1a over the workload label, so `--workload eval` and
/// `--workload inference` produce different prompt streams for the same seed.
///
/// Hand-rolled on purpose: `std::collections::hash_map::DefaultHasher` is
/// explicitly *not* stable across Rust releases, which would break the
/// byte-for-byte guarantee on a toolchain upgrade.
fn stable_hash(text: &str) -> u64 {
    const FNV_OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;
    const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;

    let mut hash = FNV_OFFSET_BASIS;
    for byte in text.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    hash
}

/// Everything that determines the generated workload.
#[derive(Debug, Clone)]
pub struct WorkloadSpec {
    /// Run name; becomes the `<runs_root>/<run_name>/` output directory.
    ///
    /// Treated as untrusted input — see [`write_workload`].
    pub run_name: String,
    /// Workload label recorded on every row, e.g. `"inference"` or `"eval"`.
    /// Also mixed into the PRNG seed.
    pub workload: String,
    /// Number of requests to generate. Must be in `1..=MAX_REQUEST_COUNT`.
    pub count: usize,
    /// PRNG seed. Identical seeds produce identical bytes.
    pub seed: u64,
    /// `max_tokens` recorded on every row (benchgen does not run inference).
    pub max_tokens: u32,
    /// `stream` flag recorded on every row.
    pub stream: bool,
}

impl WorkloadSpec {
    /// Builds a spec with the crate defaults for everything but the run name.
    pub fn new(run_name: impl Into<String>) -> Self {
        Self {
            run_name: run_name.into(),
            workload: "inference".to_string(),
            count: 32,
            seed: DEFAULT_SEED,
            max_tokens: 128,
            stream: false,
        }
    }

    /// Checks the fields that do not touch the filesystem.
    ///
    /// [`write_workload`] additionally validates `run_name` as a path.
    pub fn validate(&self) -> Result<()> {
        if self.workload.trim().is_empty() {
            bail!("workload label must not be empty");
        }
        if self.workload.len() > MAX_WORKLOAD_LABEL_LEN {
            bail!(
                "workload label of {} bytes exceeds the maximum of {MAX_WORKLOAD_LABEL_LEN}",
                self.workload.len()
            );
        }
        if self.count == 0 {
            bail!("count must be greater than 0");
        }
        if self.count > MAX_REQUEST_COUNT {
            bail!(
                "count {} exceeds the maximum of {MAX_REQUEST_COUNT}",
                self.count
            );
        }
        Ok(())
    }
}

/// One generated request. Field order here *is* the JSON field order.
#[derive(Debug, Clone, Serialize)]
pub struct WorkloadRequest {
    /// Sequential request number, 1-indexed to match the rest of the repo.
    pub request_id: u64,
    /// Workload label copied from the spec.
    pub workload: String,
    /// Seed copied from the spec, so a stray row is traceable to its run.
    pub seed: u64,
    /// The generated prompt text.
    pub prompt: String,
    /// `max_tokens` copied from the spec.
    pub max_tokens: u32,
    /// `stream` copied from the spec.
    pub stream: bool,
    /// Row schema version, see [`WORKLOAD_SCHEMA_VERSION`].
    pub schema_version: u32,
}

/// Companion manifest describing how the workload was produced.
///
/// Deliberately has no timestamp field: a timestamp would make two otherwise
/// identical runs differ on disk.
#[derive(Debug, Clone, Serialize)]
struct WorkloadManifest<'a> {
    run_name: &'a str,
    workload: &'a str,
    count: usize,
    seed: u64,
    max_tokens: u32,
    stream: bool,
    schema_version: u32,
    generator: &'a str,
    generator_version: &'a str,
}

/// Generates the workload rows in memory.
///
/// # Errors
///
/// Returns an error when the spec fails [`WorkloadSpec::validate`].
pub fn generate_workload(spec: &WorkloadSpec) -> Result<Vec<WorkloadRequest>> {
    spec.validate()?;

    let mut rng = SplitMix64::new(spec.seed ^ stable_hash(&spec.workload));
    let mut rows = Vec::with_capacity(spec.count);

    for index in 0..spec.count {
        let prompt = generate_prompt(&mut rng);
        rows.push(WorkloadRequest {
            request_id: index as u64 + 1,
            workload: spec.workload.clone(),
            seed: spec.seed,
            prompt,
            max_tokens: spec.max_tokens,
            stream: spec.stream,
            schema_version: WORKLOAD_SCHEMA_VERSION,
        });
    }

    Ok(rows)
}

/// Assembles one prompt from the `const` fragment tables.
fn generate_prompt(rng: &mut SplitMix64) -> String {
    let task = rng.pick(PROMPT_TASKS);
    let topic = rng.pick(PROMPT_TOPICS);
    let mut prompt = format!("{task} {topic}");

    // Vary the length so the workload is not a block of identical-cost rows.
    let qualifier_count = rng.next_range(MAX_QUALIFIERS + 1);
    // Draw without replacement so a prompt never repeats a clause. The
    // swap-remove is a partial Fisher-Yates shuffle: order-dependent, but
    // fully determined by the PRNG stream.
    let mut pool = PROMPT_QUALIFIERS.to_vec();
    for _ in 0..qualifier_count {
        if pool.is_empty() {
            break;
        }
        let index = rng.next_range(pool.len() as u64) as usize;
        let qualifier = pool.swap_remove(index);
        prompt.push_str("; ");
        prompt.push_str(qualifier);
    }
    prompt.push('.');
    prompt
}

/// Renders rows as JSONL: one compact JSON object per line, every line
/// (including the last) terminated by `\n`.
///
/// # Errors
///
/// Returns an error if a row fails to serialize.
pub fn render_jsonl(rows: &[WorkloadRequest]) -> Result<String> {
    let mut out = String::new();
    for row in rows {
        let line = serde_json::to_string(row)
            .with_context(|| format!("Failed to serialize request {}", row.request_id))?;
        out.push_str(&line);
        out.push('\n');
    }
    Ok(out)
}

/// Rejects a `run_name` that is anything other than a single, plain
/// directory component.
///
/// The check runs on the **pre-resolution** string, mirroring the invariant
/// in the Python `path_safety.py`: canonicalizing first would consume the
/// `..` segments, so a post-resolution check would never see the traversal it
/// is supposed to catch.
fn validate_run_name(run_name: &str) -> Result<()> {
    if run_name.trim().is_empty() {
        bail!("run_name must not be empty or whitespace-only");
    }
    if run_name.contains('/') || run_name.contains('\\') {
        bail!("run_name must not contain a path separator: {run_name:?}");
    }
    let candidate = Path::new(run_name);
    if candidate.is_absolute() {
        bail!("run_name must be a relative directory name, not an absolute path: {run_name:?}");
    }
    // Anything that is not a plain `Normal` component is `.`, `..`, a root,
    // or a drive prefix — none of which may be joined onto `runs_root`.
    if candidate
        .components()
        .any(|component| !matches!(component, Component::Normal(_)))
    {
        bail!("run_name must not contain '.', '..', or a root component: {run_name:?}");
    }
    Ok(())
}

/// Rejects `path` when it already exists as a symlink.
///
/// `validate_run_name` only clears the run_name *string*; it cannot see what
/// is already on disk at the destination. Every path this crate creates or
/// replaces is therefore checked here first, because both write primitives
/// follow links: `create_dir_all` accepts a symlink-to-directory, and
/// `fs::write` follows a symlinked file and truncates whatever it points at.
/// A pre-populated or shared runs directory is enough to plant either one.
///
/// `symlink_metadata` is the load-bearing detail — it stats the link itself,
/// where `metadata` would silently follow it and report the target.
fn reject_existing_symlink(path: &Path, label: &str) -> Result<()> {
    if fs::symlink_metadata(path).is_ok_and(|meta| meta.file_type().is_symlink()) {
        bail!(
            "{label} must be a real path, not a symlink: {}",
            path.display()
        );
    }
    Ok(())
}

/// Generates the workload and writes it under `<runs_root>/<run_name>/`.
///
/// Writes two files:
///
/// * [`WORKLOAD_FILE_NAME`] — the JSONL workload,
/// * [`WORKLOAD_MANIFEST_FILE_NAME`] — a pretty-printed JSON manifest
///   (indent 2, matching the repo-wide JSON convention).
///
/// Returns the path to the workload JSONL file.
///
/// # Errors
///
/// Returns an error when the spec is invalid, when `run_name` is not a safe
/// single directory component, or when a filesystem operation fails.
pub fn write_workload(spec: &WorkloadSpec, runs_root: &Path) -> Result<PathBuf> {
    spec.validate()?;
    // Validate before joining, never after.
    validate_run_name(&spec.run_name)?;

    let run_dir = runs_root.join(&spec.run_name);
    reject_existing_symlink(&run_dir, "run directory")?;
    fs::create_dir_all(&run_dir)
        .with_context(|| format!("Failed to create run directory {}", run_dir.display()))?;

    let workload_path = write_workload_file(spec, &run_dir)?;
    write_manifest_file(spec, &run_dir)?;

    Ok(workload_path)
}

/// Generates the rows and writes [`WORKLOAD_FILE_NAME`] into `run_dir`.
///
/// Returns the path to the workload JSONL file.
///
/// # Errors
///
/// Returns an error when the spec is invalid, when a row fails to serialize,
/// or when the write fails.
fn write_workload_file(spec: &WorkloadSpec, run_dir: &Path) -> Result<PathBuf> {
    let rows = generate_workload(spec)?;
    let workload_path = run_dir.join(WORKLOAD_FILE_NAME);
    reject_existing_symlink(&workload_path, WORKLOAD_FILE_NAME)?;
    fs::write(&workload_path, render_jsonl(&rows)?)
        .with_context(|| format!("Failed to write {}", workload_path.display()))?;
    Ok(workload_path)
}

/// Writes [`WORKLOAD_MANIFEST_FILE_NAME`] into `run_dir` as pretty-printed
/// JSON (indent 2, trailing newline), matching the repo-wide JSON convention.
///
/// # Errors
///
/// Returns an error when the manifest fails to serialize or the write fails.
fn write_manifest_file(spec: &WorkloadSpec, run_dir: &Path) -> Result<()> {
    let manifest = WorkloadManifest {
        run_name: &spec.run_name,
        workload: &spec.workload,
        count: spec.count,
        seed: spec.seed,
        max_tokens: spec.max_tokens,
        stream: spec.stream,
        schema_version: WORKLOAD_SCHEMA_VERSION,
        generator: GENERATOR_NAME,
        generator_version: env!("CARGO_PKG_VERSION"),
    };
    let manifest_path = run_dir.join(WORKLOAD_MANIFEST_FILE_NAME);
    reject_existing_symlink(&manifest_path, WORKLOAD_MANIFEST_FILE_NAME)?;
    let mut manifest_json =
        serde_json::to_string_pretty(&manifest).context("Failed to serialize workload manifest")?;
    manifest_json.push('\n');
    fs::write(&manifest_path, manifest_json)
        .with_context(|| format!("Failed to write {}", manifest_path.display()))
}

#[cfg(test)]
mod tests {
    //! Pure-logic tests only. Anything that touches the filesystem lives in
    //! `tests/`, where `CARGO_TARGET_TMPDIR` is available; a unit test here
    //! would have to fall back to the system temp directory.

    use super::*;

    fn spec_with(workload: &str, count: usize, seed: u64) -> WorkloadSpec {
        WorkloadSpec {
            run_name: "unit".to_string(),
            workload: workload.to_string(),
            count,
            seed,
            max_tokens: 128,
            stream: false,
        }
    }

    #[test]
    fn new_applies_the_documented_defaults() {
        let spec = WorkloadSpec::new("demo");
        assert_eq!(spec.run_name, "demo");
        assert_eq!(spec.workload, "inference");
        assert_eq!(spec.count, 32);
        assert_eq!(spec.seed, DEFAULT_SEED);
        assert!(spec.validate().is_ok());
    }

    #[test]
    fn validate_accepts_both_count_boundaries() {
        assert!(spec_with("inference", 1, 1).validate().is_ok());
        assert!(spec_with("inference", MAX_REQUEST_COUNT, 1)
            .validate()
            .is_ok());
    }

    #[test]
    fn validate_rejects_a_zero_count() {
        let error = spec_with("inference", 0, 1).validate().unwrap_err();
        assert!(error.to_string().contains("greater than 0"));
    }

    #[test]
    fn validate_accepts_both_label_length_boundaries() {
        let longest = "x".repeat(MAX_WORKLOAD_LABEL_LEN);
        assert!(spec_with(&longest, 1, 1).validate().is_ok());
        assert!(spec_with("x", 1, 1).validate().is_ok());
    }

    /// The label is cloned per row, so an unbounded label defeats the
    /// count-based OOM guard rather than being caught by it.
    #[test]
    fn validate_rejects_a_label_above_the_maximum() {
        let too_long = "x".repeat(MAX_WORKLOAD_LABEL_LEN + 1);
        let error = spec_with(&too_long, MAX_REQUEST_COUNT, 1)
            .validate()
            .unwrap_err();
        assert!(
            error.to_string().contains("workload label"),
            "unexpected error: {error}"
        );
    }

    #[test]
    fn validate_rejects_a_count_above_the_maximum() {
        let error = spec_with("inference", MAX_REQUEST_COUNT + 1, 1)
            .validate()
            .unwrap_err();
        assert!(error.to_string().contains("exceeds the maximum"));
    }

    #[test]
    fn validate_rejects_a_whitespace_only_workload_label() {
        for label in ["", " ", "\t\n"] {
            assert!(
                spec_with(label, 4, 1).validate().is_err(),
                "label {label:?} must be rejected"
            );
        }
    }

    #[test]
    fn generate_workload_numbers_requests_from_one_in_order() {
        let rows = generate_workload(&spec_with("inference", 5, 3)).expect("generate");
        let ids: Vec<u64> = rows.iter().map(|row| row.request_id).collect();
        assert_eq!(ids, vec![1, 2, 3, 4, 5]);
    }

    #[test]
    fn generate_workload_repeats_itself_for_the_same_spec() {
        let spec = spec_with("inference", 12, 99);
        let first = render_jsonl(&generate_workload(&spec).expect("generate")).expect("render");
        let second = render_jsonl(&generate_workload(&spec).expect("generate")).expect("render");
        assert_eq!(first, second);
    }

    #[test]
    fn render_jsonl_terminates_every_line_including_the_last() {
        let rows = generate_workload(&spec_with("inference", 3, 5)).expect("generate");
        let text = render_jsonl(&rows).expect("render");
        assert_eq!(text.matches('\n').count(), 3);
        assert!(text.ends_with('\n'));
        assert!(!text.contains("\n\n"));
    }

    #[test]
    fn render_jsonl_emits_fields_in_declaration_order() {
        // Field order is part of the byte-for-byte promise, and it is decided
        // implicitly by the order of the struct fields — a reorder during an
        // unrelated edit would go unnoticed without this exact comparison.
        let row = WorkloadRequest {
            request_id: 1,
            workload: "inference".to_string(),
            seed: 42,
            prompt: "Summarize gradient checkpointing.".to_string(),
            max_tokens: 128,
            stream: false,
            schema_version: WORKLOAD_SCHEMA_VERSION,
        };
        assert_eq!(
            render_jsonl(std::slice::from_ref(&row)).expect("render"),
            concat!(
                r#"{"request_id":1,"workload":"inference","seed":42,"#,
                r#""prompt":"Summarize gradient checkpointing.","#,
                r#""max_tokens":128,"stream":false,"schema_version":1}"#,
                "\n",
            )
        );
    }

    #[test]
    fn stable_hash_matches_its_pinned_fnv1a_values() {
        // Pinned rather than merely "stable within a process": the whole
        // reason this is hand-rolled is that `DefaultHasher` may change
        // between rustc releases, and only a literal catches that.
        assert_eq!(stable_hash("inference"), 0xdfa5_6f29_6f08_a1d4);
        assert_eq!(stable_hash("eval"), 0xd58d_0f60_840e_d8af);
        assert_eq!(stable_hash(""), 0xcbf2_9ce4_8422_2325);
    }

    #[test]
    fn stable_hash_separates_the_workload_labels() {
        assert_ne!(stable_hash("inference"), stable_hash("eval"));
    }

    #[test]
    fn next_range_stays_below_its_bound() {
        let mut rng = SplitMix64::new(1234);
        for bound in 1..=17u64 {
            for _ in 0..64 {
                assert!(rng.next_range(bound) < bound);
            }
        }
    }

    #[test]
    fn next_range_of_zero_returns_zero_instead_of_panicking() {
        let mut rng = SplitMix64::new(0);
        assert_eq!(rng.next_range(0), 0);
    }

    #[test]
    fn next_range_covers_every_residue_for_a_small_bound() {
        // Guards the rejection-sampling branch: a limit computed wrongly could
        // starve one residue class and still look random.
        let mut rng = SplitMix64::new(7);
        let mut seen = [false; 4];
        for _ in 0..256 {
            seen[rng.next_range(4) as usize] = true;
        }
        assert!(seen.iter().all(|hit| *hit));
    }

    #[test]
    fn a_prompt_never_repeats_a_qualifier_clause() {
        // The generator draws qualifiers without replacement; a swap-remove
        // bug would show up as a duplicated clause in one prompt.
        let rows = generate_workload(&spec_with("inference", 200, 2024)).expect("generate");
        for row in &rows {
            assert!(row.prompt.ends_with('.'));
            // Strip the terminating period first, or a duplicate that landed
            // in the final clause would compare unequal and slip through.
            let body = row.prompt.trim_end_matches('.');
            let clauses: Vec<&str> = body.split("; ").skip(1).collect();
            let mut unique = clauses.clone();
            unique.sort_unstable();
            unique.dedup();
            assert_eq!(
                clauses.len(),
                unique.len(),
                "repeated clause in {}",
                row.prompt
            );
            assert!(clauses.len() <= MAX_QUALIFIERS as usize);
        }
    }

    #[test]
    fn validate_run_name_accepts_a_plain_directory_component() {
        for run_name in ["run", "run-1", "run.2026-08-23", ".hidden"] {
            assert!(
                validate_run_name(run_name).is_ok(),
                "{run_name:?} should be accepted"
            );
        }
    }

    #[test]
    fn validate_run_name_rejects_traversal_and_non_component_names() {
        for run_name in ["..", "../escape", "a/b", "a\\b", "/abs", ".", "", "  "] {
            assert!(
                validate_run_name(run_name).is_err(),
                "{run_name:?} should be rejected"
            );
        }
    }
}
